### ISSUE TITLE
Use newer git, libssh2, and ruby in install.sh?

### ISSUE THREAD

**Issue by ryanpcmcquen** [jam7/chromebrew#5]
Just wondering if there is a reason not to use the newer versions included in `packages`?

**Comment by jam7** [comment]
Because of compatibility and required shared library issues.

 - It's difficult to check whether all works correctly or not from scratch on all architectures.
 - Ruby 2.4 requires gmp, readline, and ncurses.  Ruby 1.8 doesn't.
 - Updating git and libssh2 may be good idea.

**Comment by ryanpcmcquen** [comment]
>Ruby 2.4 requires gmp, readline, and ncurses. Ruby 1.8 doesn't.

Did you mean Ruby `2.0` instead of Ruby `1.8`?

**Comment by jam7** [comment]
@ryanpcmcquen Yes.  Ruby 2.0 is correct.  I was thinking about git-1.8 while writing it.  :)

**Comment by jam7** [comment]
Recently, I noticed that is is possible to update install.sh well if he/she own all machines for all architectures.  I'm not.  I could similar stuff when there is no aarch64 machines.  In near future, if we have VM environments to compile all architectures' binaries, we can do that.  Until that, I'm closing this for a while.  :)

**Comment by jam7** [comment]
FYI, I update them all to the latest binaries since we know how to cross-compile all of them now.  :)

Cross compile scripts are available at https://github.com/jam7/chrome-cross/.

**Comment by ryanpcmcquen** [comment]
Awesome!
