### ISSUE TITLE
Building gcc 7.2

### ISSUE THREAD

**Issue by ijean** [jam7/chromebrew#6]
Hi,
I'm trying to build gcc 7.2 from sources (after I've installed buildessential) but I always seem to have some linker error:

/usr/local/bin/ld: cannot find crt1.o: No such file or directory
/usr/local/bin/ld: cannot find crti.o: No such file or directory

although both files are in /usr/local/lib64.

A similar one I get when the linker tries to find libmvec_nonshared this the linker seems to search it in /usr/lib64, libmvec_nonshared is also in /usr/local/lib64

Do I need to define any environment variable prior to trying to build GCC ?

Thanks

**Comment by ijean** [comment]
BTW, I've tried adding /usr/local/lib64 to the LD_LIBRARY_PATH which didn't solved the problem.

**Comment by ijean** [comment]
Sorry for bothering you, solved by adding /usr/local/lib64 to the LIBRARY_PATH.

**Comment by ijean** [comment]
Everything seems to work now.

**Comment by jam7** [comment]
Sorry for no response about your issue, but glad to hear you manage it.  Thanks.
